#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'pio_Enable_0', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_ENABLE_0_'.
 * The prefix is the slave descriptor.
 */
#define PIO_ENABLE_0_COMPONENT_TYPE altera_avalon_pio
#define PIO_ENABLE_0_COMPONENT_NAME pio_Enable_0
#define PIO_ENABLE_0_BASE 0x0
#define PIO_ENABLE_0_SPAN 16
#define PIO_ENABLE_0_END 0xf
#define PIO_ENABLE_0_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_ENABLE_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_ENABLE_0_CAPTURE 0
#define PIO_ENABLE_0_DATA_WIDTH 1
#define PIO_ENABLE_0_DO_TEST_BENCH_WIRING 0
#define PIO_ENABLE_0_DRIVEN_SIM_VALUE 0
#define PIO_ENABLE_0_EDGE_TYPE NONE
#define PIO_ENABLE_0_FREQ 50000000
#define PIO_ENABLE_0_HAS_IN 0
#define PIO_ENABLE_0_HAS_OUT 1
#define PIO_ENABLE_0_HAS_TRI 0
#define PIO_ENABLE_0_IRQ_TYPE NONE
#define PIO_ENABLE_0_RESET_VALUE 0

/*
 * Macros for device 'pio_Reset0', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_RESET0_'.
 * The prefix is the slave descriptor.
 */
#define PIO_RESET0_COMPONENT_TYPE altera_avalon_pio
#define PIO_RESET0_COMPONENT_NAME pio_Reset0
#define PIO_RESET0_BASE 0x10
#define PIO_RESET0_SPAN 16
#define PIO_RESET0_END 0x1f
#define PIO_RESET0_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_RESET0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_RESET0_CAPTURE 0
#define PIO_RESET0_DATA_WIDTH 1
#define PIO_RESET0_DO_TEST_BENCH_WIRING 0
#define PIO_RESET0_DRIVEN_SIM_VALUE 0
#define PIO_RESET0_EDGE_TYPE NONE
#define PIO_RESET0_FREQ 50000000
#define PIO_RESET0_HAS_IN 0
#define PIO_RESET0_HAS_OUT 1
#define PIO_RESET0_HAS_TRI 0
#define PIO_RESET0_IRQ_TYPE NONE
#define PIO_RESET0_RESET_VALUE 0

/*
 * Macros for device 'pio_plaintext0', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_PLAINTEXT0_'.
 * The prefix is the slave descriptor.
 */
#define PIO_PLAINTEXT0_COMPONENT_TYPE altera_avalon_pio
#define PIO_PLAINTEXT0_COMPONENT_NAME pio_plaintext0
#define PIO_PLAINTEXT0_BASE 0x20
#define PIO_PLAINTEXT0_SPAN 16
#define PIO_PLAINTEXT0_END 0x2f
#define PIO_PLAINTEXT0_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_PLAINTEXT0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_PLAINTEXT0_CAPTURE 0
#define PIO_PLAINTEXT0_DATA_WIDTH 32
#define PIO_PLAINTEXT0_DO_TEST_BENCH_WIRING 0
#define PIO_PLAINTEXT0_DRIVEN_SIM_VALUE 0
#define PIO_PLAINTEXT0_EDGE_TYPE NONE
#define PIO_PLAINTEXT0_FREQ 50000000
#define PIO_PLAINTEXT0_HAS_IN 0
#define PIO_PLAINTEXT0_HAS_OUT 1
#define PIO_PLAINTEXT0_HAS_TRI 0
#define PIO_PLAINTEXT0_IRQ_TYPE NONE
#define PIO_PLAINTEXT0_RESET_VALUE 0

/*
 * Macros for device 'pio_plaintext1', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_PLAINTEXT1_'.
 * The prefix is the slave descriptor.
 */
#define PIO_PLAINTEXT1_COMPONENT_TYPE altera_avalon_pio
#define PIO_PLAINTEXT1_COMPONENT_NAME pio_plaintext1
#define PIO_PLAINTEXT1_BASE 0x30
#define PIO_PLAINTEXT1_SPAN 16
#define PIO_PLAINTEXT1_END 0x3f
#define PIO_PLAINTEXT1_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_PLAINTEXT1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_PLAINTEXT1_CAPTURE 0
#define PIO_PLAINTEXT1_DATA_WIDTH 32
#define PIO_PLAINTEXT1_DO_TEST_BENCH_WIRING 0
#define PIO_PLAINTEXT1_DRIVEN_SIM_VALUE 0
#define PIO_PLAINTEXT1_EDGE_TYPE NONE
#define PIO_PLAINTEXT1_FREQ 50000000
#define PIO_PLAINTEXT1_HAS_IN 0
#define PIO_PLAINTEXT1_HAS_OUT 1
#define PIO_PLAINTEXT1_HAS_TRI 0
#define PIO_PLAINTEXT1_IRQ_TYPE NONE
#define PIO_PLAINTEXT1_RESET_VALUE 0

/*
 * Macros for device 'pio_plaintext2', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_PLAINTEXT2_'.
 * The prefix is the slave descriptor.
 */
#define PIO_PLAINTEXT2_COMPONENT_TYPE altera_avalon_pio
#define PIO_PLAINTEXT2_COMPONENT_NAME pio_plaintext2
#define PIO_PLAINTEXT2_BASE 0x40
#define PIO_PLAINTEXT2_SPAN 16
#define PIO_PLAINTEXT2_END 0x4f
#define PIO_PLAINTEXT2_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_PLAINTEXT2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_PLAINTEXT2_CAPTURE 0
#define PIO_PLAINTEXT2_DATA_WIDTH 32
#define PIO_PLAINTEXT2_DO_TEST_BENCH_WIRING 0
#define PIO_PLAINTEXT2_DRIVEN_SIM_VALUE 0
#define PIO_PLAINTEXT2_EDGE_TYPE NONE
#define PIO_PLAINTEXT2_FREQ 50000000
#define PIO_PLAINTEXT2_HAS_IN 0
#define PIO_PLAINTEXT2_HAS_OUT 1
#define PIO_PLAINTEXT2_HAS_TRI 0
#define PIO_PLAINTEXT2_IRQ_TYPE NONE
#define PIO_PLAINTEXT2_RESET_VALUE 0

/*
 * Macros for device 'pio_plaintext3', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_PLAINTEXT3_'.
 * The prefix is the slave descriptor.
 */
#define PIO_PLAINTEXT3_COMPONENT_TYPE altera_avalon_pio
#define PIO_PLAINTEXT3_COMPONENT_NAME pio_plaintext3
#define PIO_PLAINTEXT3_BASE 0x50
#define PIO_PLAINTEXT3_SPAN 16
#define PIO_PLAINTEXT3_END 0x5f
#define PIO_PLAINTEXT3_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_PLAINTEXT3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_PLAINTEXT3_CAPTURE 0
#define PIO_PLAINTEXT3_DATA_WIDTH 32
#define PIO_PLAINTEXT3_DO_TEST_BENCH_WIRING 0
#define PIO_PLAINTEXT3_DRIVEN_SIM_VALUE 0
#define PIO_PLAINTEXT3_EDGE_TYPE NONE
#define PIO_PLAINTEXT3_FREQ 50000000
#define PIO_PLAINTEXT3_HAS_IN 0
#define PIO_PLAINTEXT3_HAS_OUT 1
#define PIO_PLAINTEXT3_HAS_TRI 0
#define PIO_PLAINTEXT3_IRQ_TYPE NONE
#define PIO_PLAINTEXT3_RESET_VALUE 0

/*
 * Macros for device 'pio_ciphertext3', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_CIPHERTEXT3_'.
 * The prefix is the slave descriptor.
 */
#define PIO_CIPHERTEXT3_COMPONENT_TYPE altera_avalon_pio
#define PIO_CIPHERTEXT3_COMPONENT_NAME pio_ciphertext3
#define PIO_CIPHERTEXT3_BASE 0x60
#define PIO_CIPHERTEXT3_SPAN 16
#define PIO_CIPHERTEXT3_END 0x6f
#define PIO_CIPHERTEXT3_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_CIPHERTEXT3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_CIPHERTEXT3_CAPTURE 0
#define PIO_CIPHERTEXT3_DATA_WIDTH 32
#define PIO_CIPHERTEXT3_DO_TEST_BENCH_WIRING 0
#define PIO_CIPHERTEXT3_DRIVEN_SIM_VALUE 0
#define PIO_CIPHERTEXT3_EDGE_TYPE NONE
#define PIO_CIPHERTEXT3_FREQ 50000000
#define PIO_CIPHERTEXT3_HAS_IN 1
#define PIO_CIPHERTEXT3_HAS_OUT 0
#define PIO_CIPHERTEXT3_HAS_TRI 0
#define PIO_CIPHERTEXT3_IRQ_TYPE NONE
#define PIO_CIPHERTEXT3_RESET_VALUE 0

/*
 * Macros for device 'pio_ciphertext2', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_CIPHERTEXT2_'.
 * The prefix is the slave descriptor.
 */
#define PIO_CIPHERTEXT2_COMPONENT_TYPE altera_avalon_pio
#define PIO_CIPHERTEXT2_COMPONENT_NAME pio_ciphertext2
#define PIO_CIPHERTEXT2_BASE 0x70
#define PIO_CIPHERTEXT2_SPAN 16
#define PIO_CIPHERTEXT2_END 0x7f
#define PIO_CIPHERTEXT2_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_CIPHERTEXT2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_CIPHERTEXT2_CAPTURE 0
#define PIO_CIPHERTEXT2_DATA_WIDTH 32
#define PIO_CIPHERTEXT2_DO_TEST_BENCH_WIRING 0
#define PIO_CIPHERTEXT2_DRIVEN_SIM_VALUE 0
#define PIO_CIPHERTEXT2_EDGE_TYPE NONE
#define PIO_CIPHERTEXT2_FREQ 50000000
#define PIO_CIPHERTEXT2_HAS_IN 1
#define PIO_CIPHERTEXT2_HAS_OUT 0
#define PIO_CIPHERTEXT2_HAS_TRI 0
#define PIO_CIPHERTEXT2_IRQ_TYPE NONE
#define PIO_CIPHERTEXT2_RESET_VALUE 0

/*
 * Macros for device 'pio_ciphertext1', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_CIPHERTEXT1_'.
 * The prefix is the slave descriptor.
 */
#define PIO_CIPHERTEXT1_COMPONENT_TYPE altera_avalon_pio
#define PIO_CIPHERTEXT1_COMPONENT_NAME pio_ciphertext1
#define PIO_CIPHERTEXT1_BASE 0x80
#define PIO_CIPHERTEXT1_SPAN 16
#define PIO_CIPHERTEXT1_END 0x8f
#define PIO_CIPHERTEXT1_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_CIPHERTEXT1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_CIPHERTEXT1_CAPTURE 0
#define PIO_CIPHERTEXT1_DATA_WIDTH 32
#define PIO_CIPHERTEXT1_DO_TEST_BENCH_WIRING 0
#define PIO_CIPHERTEXT1_DRIVEN_SIM_VALUE 0
#define PIO_CIPHERTEXT1_EDGE_TYPE NONE
#define PIO_CIPHERTEXT1_FREQ 50000000
#define PIO_CIPHERTEXT1_HAS_IN 1
#define PIO_CIPHERTEXT1_HAS_OUT 0
#define PIO_CIPHERTEXT1_HAS_TRI 0
#define PIO_CIPHERTEXT1_IRQ_TYPE NONE
#define PIO_CIPHERTEXT1_RESET_VALUE 0

/*
 * Macros for device 'pio_ciphertext0', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_CIPHERTEXT0_'.
 * The prefix is the slave descriptor.
 */
#define PIO_CIPHERTEXT0_COMPONENT_TYPE altera_avalon_pio
#define PIO_CIPHERTEXT0_COMPONENT_NAME pio_ciphertext0
#define PIO_CIPHERTEXT0_BASE 0x90
#define PIO_CIPHERTEXT0_SPAN 16
#define PIO_CIPHERTEXT0_END 0x9f
#define PIO_CIPHERTEXT0_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_CIPHERTEXT0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_CIPHERTEXT0_CAPTURE 0
#define PIO_CIPHERTEXT0_DATA_WIDTH 32
#define PIO_CIPHERTEXT0_DO_TEST_BENCH_WIRING 0
#define PIO_CIPHERTEXT0_DRIVEN_SIM_VALUE 0
#define PIO_CIPHERTEXT0_EDGE_TYPE NONE
#define PIO_CIPHERTEXT0_FREQ 50000000
#define PIO_CIPHERTEXT0_HAS_IN 1
#define PIO_CIPHERTEXT0_HAS_OUT 0
#define PIO_CIPHERTEXT0_HAS_TRI 0
#define PIO_CIPHERTEXT0_IRQ_TYPE NONE
#define PIO_CIPHERTEXT0_RESET_VALUE 0

/*
 * Macros for device 'pio_key15', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY15_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY15_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY15_COMPONENT_NAME pio_key15
#define PIO_KEY15_BASE 0xa0
#define PIO_KEY15_SPAN 16
#define PIO_KEY15_END 0xaf
#define PIO_KEY15_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY15_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY15_CAPTURE 0
#define PIO_KEY15_DATA_WIDTH 8
#define PIO_KEY15_DO_TEST_BENCH_WIRING 0
#define PIO_KEY15_DRIVEN_SIM_VALUE 0
#define PIO_KEY15_EDGE_TYPE NONE
#define PIO_KEY15_FREQ 50000000
#define PIO_KEY15_HAS_IN 0
#define PIO_KEY15_HAS_OUT 1
#define PIO_KEY15_HAS_TRI 0
#define PIO_KEY15_IRQ_TYPE NONE
#define PIO_KEY15_RESET_VALUE 0

/*
 * Macros for device 'pio_key14', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY14_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY14_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY14_COMPONENT_NAME pio_key14
#define PIO_KEY14_BASE 0xb0
#define PIO_KEY14_SPAN 16
#define PIO_KEY14_END 0xbf
#define PIO_KEY14_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY14_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY14_CAPTURE 0
#define PIO_KEY14_DATA_WIDTH 8
#define PIO_KEY14_DO_TEST_BENCH_WIRING 0
#define PIO_KEY14_DRIVEN_SIM_VALUE 0
#define PIO_KEY14_EDGE_TYPE NONE
#define PIO_KEY14_FREQ 50000000
#define PIO_KEY14_HAS_IN 0
#define PIO_KEY14_HAS_OUT 1
#define PIO_KEY14_HAS_TRI 0
#define PIO_KEY14_IRQ_TYPE NONE
#define PIO_KEY14_RESET_VALUE 0

/*
 * Macros for device 'pio_key13', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY13_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY13_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY13_COMPONENT_NAME pio_key13
#define PIO_KEY13_BASE 0xc0
#define PIO_KEY13_SPAN 16
#define PIO_KEY13_END 0xcf
#define PIO_KEY13_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY13_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY13_CAPTURE 0
#define PIO_KEY13_DATA_WIDTH 8
#define PIO_KEY13_DO_TEST_BENCH_WIRING 0
#define PIO_KEY13_DRIVEN_SIM_VALUE 0
#define PIO_KEY13_EDGE_TYPE NONE
#define PIO_KEY13_FREQ 50000000
#define PIO_KEY13_HAS_IN 0
#define PIO_KEY13_HAS_OUT 1
#define PIO_KEY13_HAS_TRI 0
#define PIO_KEY13_IRQ_TYPE NONE
#define PIO_KEY13_RESET_VALUE 0

/*
 * Macros for device 'pio_key12', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY12_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY12_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY12_COMPONENT_NAME pio_key12
#define PIO_KEY12_BASE 0xd0
#define PIO_KEY12_SPAN 16
#define PIO_KEY12_END 0xdf
#define PIO_KEY12_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY12_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY12_CAPTURE 0
#define PIO_KEY12_DATA_WIDTH 8
#define PIO_KEY12_DO_TEST_BENCH_WIRING 0
#define PIO_KEY12_DRIVEN_SIM_VALUE 0
#define PIO_KEY12_EDGE_TYPE NONE
#define PIO_KEY12_FREQ 50000000
#define PIO_KEY12_HAS_IN 0
#define PIO_KEY12_HAS_OUT 1
#define PIO_KEY12_HAS_TRI 0
#define PIO_KEY12_IRQ_TYPE NONE
#define PIO_KEY12_RESET_VALUE 0

/*
 * Macros for device 'pio_key11', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY11_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY11_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY11_COMPONENT_NAME pio_key11
#define PIO_KEY11_BASE 0xe0
#define PIO_KEY11_SPAN 16
#define PIO_KEY11_END 0xef
#define PIO_KEY11_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY11_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY11_CAPTURE 0
#define PIO_KEY11_DATA_WIDTH 8
#define PIO_KEY11_DO_TEST_BENCH_WIRING 0
#define PIO_KEY11_DRIVEN_SIM_VALUE 0
#define PIO_KEY11_EDGE_TYPE NONE
#define PIO_KEY11_FREQ 50000000
#define PIO_KEY11_HAS_IN 0
#define PIO_KEY11_HAS_OUT 1
#define PIO_KEY11_HAS_TRI 0
#define PIO_KEY11_IRQ_TYPE NONE
#define PIO_KEY11_RESET_VALUE 0

/*
 * Macros for device 'pio_key10', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY10_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY10_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY10_COMPONENT_NAME pio_key10
#define PIO_KEY10_BASE 0xf0
#define PIO_KEY10_SPAN 16
#define PIO_KEY10_END 0xff
#define PIO_KEY10_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY10_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY10_CAPTURE 0
#define PIO_KEY10_DATA_WIDTH 8
#define PIO_KEY10_DO_TEST_BENCH_WIRING 0
#define PIO_KEY10_DRIVEN_SIM_VALUE 0
#define PIO_KEY10_EDGE_TYPE NONE
#define PIO_KEY10_FREQ 50000000
#define PIO_KEY10_HAS_IN 0
#define PIO_KEY10_HAS_OUT 1
#define PIO_KEY10_HAS_TRI 0
#define PIO_KEY10_IRQ_TYPE NONE
#define PIO_KEY10_RESET_VALUE 0

/*
 * Macros for device 'pio_key9', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY9_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY9_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY9_COMPONENT_NAME pio_key9
#define PIO_KEY9_BASE 0x100
#define PIO_KEY9_SPAN 16
#define PIO_KEY9_END 0x10f
#define PIO_KEY9_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY9_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY9_CAPTURE 0
#define PIO_KEY9_DATA_WIDTH 8
#define PIO_KEY9_DO_TEST_BENCH_WIRING 0
#define PIO_KEY9_DRIVEN_SIM_VALUE 0
#define PIO_KEY9_EDGE_TYPE NONE
#define PIO_KEY9_FREQ 50000000
#define PIO_KEY9_HAS_IN 0
#define PIO_KEY9_HAS_OUT 1
#define PIO_KEY9_HAS_TRI 0
#define PIO_KEY9_IRQ_TYPE NONE
#define PIO_KEY9_RESET_VALUE 0

/*
 * Macros for device 'pio_key8', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY8_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY8_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY8_COMPONENT_NAME pio_key8
#define PIO_KEY8_BASE 0x110
#define PIO_KEY8_SPAN 16
#define PIO_KEY8_END 0x11f
#define PIO_KEY8_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY8_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY8_CAPTURE 0
#define PIO_KEY8_DATA_WIDTH 8
#define PIO_KEY8_DO_TEST_BENCH_WIRING 0
#define PIO_KEY8_DRIVEN_SIM_VALUE 0
#define PIO_KEY8_EDGE_TYPE NONE
#define PIO_KEY8_FREQ 50000000
#define PIO_KEY8_HAS_IN 0
#define PIO_KEY8_HAS_OUT 1
#define PIO_KEY8_HAS_TRI 0
#define PIO_KEY8_IRQ_TYPE NONE
#define PIO_KEY8_RESET_VALUE 0

/*
 * Macros for device 'pio_key7', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY7_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY7_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY7_COMPONENT_NAME pio_key7
#define PIO_KEY7_BASE 0x120
#define PIO_KEY7_SPAN 16
#define PIO_KEY7_END 0x12f
#define PIO_KEY7_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY7_CAPTURE 0
#define PIO_KEY7_DATA_WIDTH 8
#define PIO_KEY7_DO_TEST_BENCH_WIRING 0
#define PIO_KEY7_DRIVEN_SIM_VALUE 0
#define PIO_KEY7_EDGE_TYPE NONE
#define PIO_KEY7_FREQ 50000000
#define PIO_KEY7_HAS_IN 0
#define PIO_KEY7_HAS_OUT 1
#define PIO_KEY7_HAS_TRI 0
#define PIO_KEY7_IRQ_TYPE NONE
#define PIO_KEY7_RESET_VALUE 0

/*
 * Macros for device 'pio_key6', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY6_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY6_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY6_COMPONENT_NAME pio_key6
#define PIO_KEY6_BASE 0x130
#define PIO_KEY6_SPAN 16
#define PIO_KEY6_END 0x13f
#define PIO_KEY6_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY6_CAPTURE 0
#define PIO_KEY6_DATA_WIDTH 8
#define PIO_KEY6_DO_TEST_BENCH_WIRING 0
#define PIO_KEY6_DRIVEN_SIM_VALUE 0
#define PIO_KEY6_EDGE_TYPE NONE
#define PIO_KEY6_FREQ 50000000
#define PIO_KEY6_HAS_IN 0
#define PIO_KEY6_HAS_OUT 1
#define PIO_KEY6_HAS_TRI 0
#define PIO_KEY6_IRQ_TYPE NONE
#define PIO_KEY6_RESET_VALUE 0

/*
 * Macros for device 'pio_key5', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY5_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY5_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY5_COMPONENT_NAME pio_key5
#define PIO_KEY5_BASE 0x140
#define PIO_KEY5_SPAN 16
#define PIO_KEY5_END 0x14f
#define PIO_KEY5_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY5_CAPTURE 0
#define PIO_KEY5_DATA_WIDTH 8
#define PIO_KEY5_DO_TEST_BENCH_WIRING 0
#define PIO_KEY5_DRIVEN_SIM_VALUE 0
#define PIO_KEY5_EDGE_TYPE NONE
#define PIO_KEY5_FREQ 50000000
#define PIO_KEY5_HAS_IN 0
#define PIO_KEY5_HAS_OUT 1
#define PIO_KEY5_HAS_TRI 0
#define PIO_KEY5_IRQ_TYPE NONE
#define PIO_KEY5_RESET_VALUE 0

/*
 * Macros for device 'pio_key4', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY4_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY4_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY4_COMPONENT_NAME pio_key4
#define PIO_KEY4_BASE 0x150
#define PIO_KEY4_SPAN 16
#define PIO_KEY4_END 0x15f
#define PIO_KEY4_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY4_CAPTURE 0
#define PIO_KEY4_DATA_WIDTH 8
#define PIO_KEY4_DO_TEST_BENCH_WIRING 0
#define PIO_KEY4_DRIVEN_SIM_VALUE 0
#define PIO_KEY4_EDGE_TYPE NONE
#define PIO_KEY4_FREQ 50000000
#define PIO_KEY4_HAS_IN 0
#define PIO_KEY4_HAS_OUT 1
#define PIO_KEY4_HAS_TRI 0
#define PIO_KEY4_IRQ_TYPE NONE
#define PIO_KEY4_RESET_VALUE 0

/*
 * Macros for device 'pio_key3', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY3_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY3_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY3_COMPONENT_NAME pio_key3
#define PIO_KEY3_BASE 0x160
#define PIO_KEY3_SPAN 16
#define PIO_KEY3_END 0x16f
#define PIO_KEY3_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY3_CAPTURE 0
#define PIO_KEY3_DATA_WIDTH 8
#define PIO_KEY3_DO_TEST_BENCH_WIRING 0
#define PIO_KEY3_DRIVEN_SIM_VALUE 0
#define PIO_KEY3_EDGE_TYPE NONE
#define PIO_KEY3_FREQ 50000000
#define PIO_KEY3_HAS_IN 0
#define PIO_KEY3_HAS_OUT 1
#define PIO_KEY3_HAS_TRI 0
#define PIO_KEY3_IRQ_TYPE NONE
#define PIO_KEY3_RESET_VALUE 0

/*
 * Macros for device 'pio_key2', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY2_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY2_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY2_COMPONENT_NAME pio_key2
#define PIO_KEY2_BASE 0x170
#define PIO_KEY2_SPAN 16
#define PIO_KEY2_END 0x17f
#define PIO_KEY2_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY2_CAPTURE 0
#define PIO_KEY2_DATA_WIDTH 8
#define PIO_KEY2_DO_TEST_BENCH_WIRING 0
#define PIO_KEY2_DRIVEN_SIM_VALUE 0
#define PIO_KEY2_EDGE_TYPE NONE
#define PIO_KEY2_FREQ 50000000
#define PIO_KEY2_HAS_IN 0
#define PIO_KEY2_HAS_OUT 1
#define PIO_KEY2_HAS_TRI 0
#define PIO_KEY2_IRQ_TYPE NONE
#define PIO_KEY2_RESET_VALUE 0

/*
 * Macros for device 'pio_key1', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY1_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY1_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY1_COMPONENT_NAME pio_key1
#define PIO_KEY1_BASE 0x180
#define PIO_KEY1_SPAN 16
#define PIO_KEY1_END 0x18f
#define PIO_KEY1_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY1_CAPTURE 0
#define PIO_KEY1_DATA_WIDTH 8
#define PIO_KEY1_DO_TEST_BENCH_WIRING 0
#define PIO_KEY1_DRIVEN_SIM_VALUE 0
#define PIO_KEY1_EDGE_TYPE NONE
#define PIO_KEY1_FREQ 50000000
#define PIO_KEY1_HAS_IN 0
#define PIO_KEY1_HAS_OUT 1
#define PIO_KEY1_HAS_TRI 0
#define PIO_KEY1_IRQ_TYPE NONE
#define PIO_KEY1_RESET_VALUE 0

/*
 * Macros for device 'pio_key0', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_KEY0_'.
 * The prefix is the slave descriptor.
 */
#define PIO_KEY0_COMPONENT_TYPE altera_avalon_pio
#define PIO_KEY0_COMPONENT_NAME pio_key0
#define PIO_KEY0_BASE 0x190
#define PIO_KEY0_SPAN 16
#define PIO_KEY0_END 0x19f
#define PIO_KEY0_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_KEY0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_KEY0_CAPTURE 0
#define PIO_KEY0_DATA_WIDTH 8
#define PIO_KEY0_DO_TEST_BENCH_WIRING 0
#define PIO_KEY0_DRIVEN_SIM_VALUE 0
#define PIO_KEY0_EDGE_TYPE NONE
#define PIO_KEY0_FREQ 50000000
#define PIO_KEY0_HAS_IN 0
#define PIO_KEY0_HAS_OUT 1
#define PIO_KEY0_HAS_TRI 0
#define PIO_KEY0_IRQ_TYPE NONE
#define PIO_KEY0_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1765491152

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 0
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
